export enum AuditCategory {
  AUTH = 'AUTH',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  VEHICLE_MANAGEMENT = 'VEHICLE_MANAGEMENT',
  ROUTE_MANAGEMENT = 'ROUTE_MANAGEMENT',
  DELIVERY_MANAGEMENT = 'DELIVERY_MANAGEMENT',
  CUSTOMER_MANAGEMENT = 'CUSTOMER_MANAGEMENT',
  DRIVER_MANAGEMENT = 'DRIVER_MANAGEMENT',
  INCIDENT_MANAGEMENT = 'INCIDENT_MANAGEMENT',
  SYSTEM = 'SYSTEM',
}
